version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
        environment:
          GO111MODULE: "on"
    working_directory: /go/src/github.com/meinto/glow
    steps:
      - checkout
      - run: go get ./...
      - run: GOOS=darwin go build .
      - run: ls -la